version: '3.9'

services:
  frontend:
    build:
      context: .
      dockerfile: chessfrontend/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: webChess/Dockerfile
    ports:
      - "8000:8000"
